var AccessControlService=(function(){
  function activeAssignments_(){var today=nowIso_().slice(0,10);var activeEmployees={};AccessControlRepository.readTable('Employees').filter(function(r){return String(r.active).toLowerCase()==='true';}).forEach(function(r){activeEmployees[normalizeEmail_(r.email)]=true;});var activeRoles={};AccessControlRepository.readTable('Roles').filter(function(r){return String(r.active).toLowerCase()==='true';}).forEach(function(r){activeRoles[String(r.role_id)]=true;});return AccessControlRepository.readTable('RoleAssignments').filter(function(r){var email=normalizeEmail_(r.employee_email);return activeEmployees[email]&&activeRoles[String(r.role_id)]&&String(r.active).toLowerCase()==='true'&&(!r.effective_from||String(r.effective_from).slice(0,10)<=today)&&(!r.effective_to||String(r.effective_to).slice(0,10)>=today);});}
  function desired_(){var assignments=activeAssignments_();var matrix=AccessControlRepository.readTable('FolderAccessMatrix').filter(function(r){return String(r.active).toLowerCase()==='true';});var byIdentity={};assignments.forEach(function(a){matrix.filter(function(m){return String(m.role_id)===String(a.role_id);}).forEach(function(m){var grant={email:normalizeEmail_(a.employee_email),folderId:String(m.folder_id),permission:String(m.permission).toUpperCase()};var key=grant.folderId+':'+grant.email;var existing=byIdentity[key];if(!existing||grant.permission==='EDITOR')byIdentity[key]=grant;});});return Object.keys(byIdentity).map(function(key){return byIdentity[key];});}
  function protectedEmails_(){var emails=ConfigService.protectedEmails().slice();var effective=normalizeEmail_(Session.getEffectiveUser().getEmail());if(effective)emails.push(effective);AccessControlRepository.readTable('Employees').filter(function(r){return String(r.active).toLowerCase()==='true'&&['ADMIN','CONTENT_MANAGER'].indexOf(String(r.role_id))>=0;}).forEach(function(r){emails.push(normalizeEmail_(r.email));});activeAssignments_().filter(function(r){return ['ADMIN','CONTENT_MANAGER'].indexOf(String(r.role_id))>=0;}).forEach(function(r){emails.push(normalizeEmail_(r.employee_email));});return emails.filter(function(email,index,all){return email&&all.indexOf(email)===index;});}
  function current_(folderIds){var grants=[];folderIds.forEach(function(id){try{var result=Drive.Permissions.list(id,{fields:'permissions(id,emailAddress,role,type)'});(result.permissions||[]).filter(function(p){return p.type==='user'&&p.emailAddress;}).forEach(function(p){grants.push({email:normalizeEmail_(p.emailAddress),folderId:id,permission:p.role==='writer'?'EDITOR':'VIEWER',permissionId:p.id});});}catch(e){throw ErrorService.create('ACL_SYNC_FAILED','Cannot read permissions for '+id);}});return grants;}
  function diff_(){var desired=desired_();var folderIds=[].filter.call(desired.map(function(g){return g.folderId;}),function(v,i,a){return a.indexOf(v)===i;});var current=current_(folderIds);var wanted={};desired.forEach(function(g){wanted[g.folderId+':'+g.email]=g;});var existing={};current.forEach(function(g){existing[g.folderId+':'+g.email]=g;});var protectedEmails=protectedEmails_();var result={add:[],change:[],remove:[],protected:[]};desired.forEach(function(g){var c=existing[g.folderId+':'+g.email];if(!c)result.add.push(g);else if(c.permission!==g.permission)result.change.push(Object.assign({},g,{permissionId:c.permissionId}));});current.forEach(function(g){if(!wanted[g.folderId+':'+g.email]){if(protectedEmails.indexOf(g.email)>=0||ConfigService.get('ALLOW_ACL_REMOVAL')!=='true')result.protected.push(g);else result.remove.push(g);}});return result;}
  function preview(){AuthService.authorize(true);return diff_();}
  function sync(){var user=AuthService.authorize(true);var diff=diff_();AuditRepository.record('ACL_SYNC_STARTED',user.email,'',null,null,{counts:{add:diff.add.length,change:diff.change.length,remove:diff.remove.length}},'SUCCESS','');try{diff.add.forEach(function(g){Drive.Permissions.create({type:'user',role:g.permission==='EDITOR'?'writer':'reader',emailAddress:g.email},g.folderId,{sendNotificationEmail:false});AuditRepository.record('ACL_ADDED',user.email,'',null,g,{},'SUCCESS','');});diff.change.forEach(function(g){Drive.Permissions.update({role:g.permission==='EDITOR'?'writer':'reader'},g.folderId,g.permissionId);AuditRepository.record('ACL_CHANGED',user.email,'',null,g,{},'SUCCESS','');});diff.remove.forEach(function(g){Drive.Permissions.remove(g.folderId,g.permissionId);AuditRepository.record('ACL_REMOVED',user.email,'',g,null,{},'SUCCESS','');});AuditRepository.record('ACL_SYNC_COMPLETED',user.email,'',null,null,{counts:{add:diff.add.length,change:diff.change.length,remove:diff.remove.length}},'SUCCESS','');return diff;}catch(e){AuditRepository.record('ACL_SYNC_COMPLETED',user.email,'',null,null,{},'FAILURE','ACL_SYNC_FAILED');throw ErrorService.create('ACL_SYNC_FAILED',e.message);}}
  return {preview:preview,sync:sync};
})();
